
ffprobe -i track-1.mp3            -show_entries format=duration -v quiet -of csv="p=0"
ffprobe -i track-2.mp3    -show_entries format=duration -v quiet -of csv="p=0"
ffprobe -i track-3.mp3    -show_entries format=duration -v quiet -of csv="p=0"
ffprobe -i track-4-2.mp3    -show_entries format=duration -v quiet -of csv="p=0"
ffprobe -i track-4.mp3    -show_entries format=duration -v quiet -of csv="p=0"
ffprobe -i track-5-2.mp3    -show_entries format=duration -v quiet -of csv="p=0"
ffprobe -i track-5.mp3    -show_entries format=duration -v quiet -of csv="p=0"
ffprobe -i track-6-2.mp3    -show_entries format=duration -v quiet -of csv="p=0"
ffprobe -i track-6.mp3    -show_entries format=duration -v quiet -of csv="p=0"
ffprobe -i track-7-2.mp3    -show_entries format=duration -v quiet -of csv="p=0"
ffprobe -i track-7.mp3    -show_entries format=duration -v quiet -of csv="p=0"
